variables:
  DOCKER_DRIVER: overlay2
  PACKAGES_LIST: tracetools_analysis ros2trace_analysis
  BASE_IMAGE_ID: registry.gitlab.com/micro-ros/ros_tracing/ci_base
  DISTRO: foxy
  ROS2TRACING_BRANCH: master

.global_artifacts: &global_artifacts
  artifacts:
    paths:
      - install
      - build/*/test_results/*/*.xunit.xml
      - build/*/pytest.xml
    reports:
      junit:
        - build/*/test_results/*/*.xunit.xml
        - build/*/pytest.xml

build:
  image: $BASE_IMAGE_ID:$DISTRO
  before_script:
    - . /root/ws/install/local_setup.sh
  script:
    - python3 get_branch.py --check
    - git clone https://gitlab.com/micro-ROS/ros_tracing/ros2_tracing.git --branch $(python3 get_branch.py)
    - colcon build --symlink-install --event-handlers console_cohesion+ --packages-up-to $PACKAGES_LIST
    - colcon test --event-handlers console_cohesion+ --packages-select $PACKAGES_LIST
    - colcon test-result --all
  <<: *global_artifacts
