image: registry.gitlab.com/micro-ros/ros_tracing/ci_base

variables:
  DOCKER_DRIVER: overlay2
  PACKAGES_LIST: tracetools_analysis

before_script:
  - git clone https://gitlab.com/micro-ROS/ros_tracing/ros2_tracing.git
  - rosdep install --from-paths . -i . -i /root/ws --rosdistro dashing -y
  - . /root/ws/install/local_setup.sh

build:
  script:
    - colcon build --symlink-install --packages-up-to $PACKAGES_LIST
    - . install/local_setup.sh
    - colcon test --packages-select $PACKAGES_LIST
    - colcon test-result
  artifacts:
    paths:
      - install
      - build/*/test_results/*/*.xunit.xml
      - build/*/pytest.xml
    reports:
      junit:
        - build/*/test_results/*/*.xunit.xml
        - build/*/pytest.xml
