variables:
  DOCKER_DRIVER: overlay2
  PACKAGES_LIST: tracetools_analysis
  base_image_id: registry.gitlab.com/micro-ros/ros_tracing/ci_base

build:
  image: $base_image_id
  before_script:
    - git clone https://gitlab.com/micro-ROS/ros_tracing/ros2_tracing.git
    - . /root/ws/install/local_setup.sh
  script:
    - colcon build --symlink-install --packages-up-to $PACKAGES_LIST
    - . install/local_setup.sh
    - colcon test --packages-select $PACKAGES_LIST
    - colcon test-result --all
  artifacts:
    paths:
      - install
      - build/*/test_results/*/*.xunit.xml
      - build/*/pytest.xml
    reports:
      junit:
        - build/*/test_results/*/*.xunit.xml
        - build/*/pytest.xml
