variables:
  DOCKER_DRIVER: overlay2
  PACKAGES_LIST: tracetools_analysis ros2trace_analysis
  BASE_IMAGE_ID: registry.gitlab.com/micro-ros/ros_tracing/ci_base
  DISTRO: dashing
  ROS2TRACING_BRANCH: $DISTRO

.global_artifacts: &global_artifacts
  artifacts:
    paths:
      - install
      - build/*/test_results/*/*.xunit.xml
      - build/*/pytest.xml
    reports:
      junit:
        - build/*/test_results/*/*.xunit.xml
        - build/*/pytest.xml

build:
  image: $BASE_IMAGE_ID:$DISTRO
  before_script:
    - git clone https://gitlab.com/micro-ROS/ros_tracing/ros2_tracing.git --branch $ROS2TRACING_BRANCH
    - . /root/ws/install/local_setup.sh
  script:
    - colcon build --symlink-install --packages-up-to $PACKAGES_LIST
    - colcon test --packages-select $PACKAGES_LIST --pytest-args -o addopts=
    - colcon test-result --all
  <<: *global_artifacts
